n_imgs_train: 20
n_imgs_val: 20
crop_size_train: [96, 96, 48]
crop_size_val: [96, 96, 48]
attn_heads: 2
attn_layers: 2
use_proj_occ: False

ckpt: null
ckpt_dir: "./ckpts/IOAR"
model_name: IOAR
seed: 0
use_amp: True

initial_epochs: 350
initial_lr: .001
initial_batch_size: 4

finetune_epochs: 150
finetune_lr: .0001
finetune_batch_size: 2

wandb_project_name: "IOAR"

scannet_dir: "/path/to/processed_scannet_data"
tsdf_dir: "/path/to/tsdf_data"
